# Generated by Django 5.2.8 on 2025-11-22 23:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(verbose_name='Approvel Level')),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20, verbose_name='Approval Status')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Finance Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Purchase Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description...')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Request Status')),
                ('proforma_invoice', models.FileField(blank=True, null=True, upload_to='proforma/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'pdf', 'ppt', 'docx', 'xlsx'])], verbose_name='Proforma Invoice File')),
                ('purchase_order', models.FileField(blank=True, null=True, upload_to='purchase_orders/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'pdf', 'ppt', 'docx', 'xlsx'])], verbose_name='Purchase Order')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'pdf', 'ppt', 'docx', 'xlsx'])], verbose_name='Receipt File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='Item Name')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit Price')),
            ],
        ),
    ]
