# Generated by Django 5.2.8 on 2025-11-22 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstep',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_requests', to=settings.AUTH_USER_MODEL, verbose_name='Approver'),
        ),
        migrations.AddField(
            model_name='financenote',
            name='finance_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_notes_created', to=settings.AUTH_USER_MODEL, verbose_name='Finance Officer'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requested By'),
        ),
        migrations.AddField(
            model_name='financenote',
            name='purchase_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_notes', to='purchases.purchaserequest', verbose_name='Purchase Request'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='purchase_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='purchases.purchaserequest', verbose_name='Purchase Request'),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='purchase_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaserequest', verbose_name='Purchase Request'),
        ),
    ]
