# Generated by Django 5.2.8 on 2025-11-24 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financenote',
            name='purchase_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_notes', to='purchases.purchaserequest', verbose_name='Purchase Request'),
        ),
    ]
