# Generated by Django 5.2.8 on 2025-11-27 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_alter_financenote_purchase_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Policy Title')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Amount')),
                ('max_amount', models.DecimalField(decimal_places=2, default=999999999, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum Amount')),
                ('required_approval_levels', models.PositiveIntegerField(default=2, verbose_name='Approval Levels')),
                ('active', models.BooleanField(default=True, verbose_name='Active Policy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['min_amount'],
            },
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='level',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Approvel Level'),
        ),
    ]
