# Generated by Django 5.2.8 on 2025-11-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_alter_purchaserequest_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Amount'),
        ),
    ]
