# Generated by Django 5.2.8 on 2025-11-27 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_alter_purchaserequest_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financenote',
            name='purchase_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_notes', to='purchases.purchaserequest', verbose_name='Purchase Request'),
        ),
    ]
